# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sampleiOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sampleiOS
  pod 'EnxRTCiOS'
  pod 'Socket.IO-Client-Swift', '~> 15.0.0'
  pod 'SVProgressHUD'
  pod 'ReachabilitySwift'
  pod 'Crashlytics'
  pod 'AMBubbleTableViewController'

  target 'sampleiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sampleiOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
